name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  image:
    needs: test
    uses: ./.github/workflows/image.yml
    permissions:
      contents: read
      packages: write
    with:
      publish: ${{ github.event_name != 'pull_request' }}
